name: Repository Info
on:  workflow_dispatch
jobs:
  repository:
    runs-on: ubuntu-latest
    steps:
      - name: print repository owner
        run: echo "${{ toJson(github.repository.owner) }}"
      - name: print repository name
        run: echo "${{ toJson(github.repository.name) }}"
