name: Download Workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] 
  workflow_dispatch:
env:
  ARTIFACT_PATH: ${{ secrets.ARTIFACT_PATH }}
  ARTIFACT_NAME: ${{ vars.ARTIFACT_NAME }}
jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:    
      - name: print github object
        id: prod-out
        run: echo "owner=${{github.event.repository_name}}" >> GITHUB_OUTPUT
      
      - name: read output
        run: echo "owner=${{steps.prod-out.outputs.owner}}" >> ${{ env.ARTIFACT_PATH }}
     
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ${{ env.ARTIFACT_PATH }}
          name: ${{ env.ARTIFACT_NAME }}
              
  get-artifact:
    needs: create-artifact
    runs-on: ubuntu-latest
    steps: 
     - name: download artifact     
       uses: actions/download-artifact@v4       
       with:
         name: ${{ env.ARTIFACT_NAME }}
         
     - name: read file
       run: cat ${{ env.ARTIFACT_PATH }}
     
